import { DropdownItemProps } from "semantic-ui-react";

export type Statement = {
  id: string;
  label: string;
  createDate: string;
  payments?: {};
};

export type Payment = {
  id: string;
  label: string;
  amount: number;
  type:
    | "salary"
    | "home"
    | "gaselectricity"
    | "foodrace"
    | "mobile"
    | "internet"
    | "movie"
    | "music"
    | "car"
    | "bar"
    | "medkit"
    | "pet"
    | "restaurant"
    | "viedogame"
    | "donation"
    | "university"
    | "transport"
    | "travel"
    | "onlineshopping"
    | "shopping"
    | "sport"
    | "credit"
    | "insurance"
    | "gavel"
    | "cut"
    | "newspaper"
    | "withdrawal"
    | "other"
    | string;
  debit: boolean;
  active: boolean;
};

export const getLabelOfType = (type: string): string => {
  const paymentOptionFind = PaymentOptions.find(
    (paymentOption) => paymentOption.value === type
  );
  return paymentOptionFind !== undefined && paymentOptionFind.text
    ? (paymentOptionFind.text as string)
    : "error.label.type.not.found";
};

export const AlgoTypePayment = (key: string, defaultvalue: string): string => {
  if (key === "") return "other";
  if (key.length < 2) {
    return defaultvalue;
  }

  const valSplit = key.split(" ");
  for (let i = 0; i < valSplit.length; i++) {
    const val = valSplit[i];
    const wordWithTwoDefinitionFind = wordWithTwoDefinition.find(
      (def) => def.key === val
    );
    if (wordWithTwoDefinitionFind !== undefined) {
      if (valSplit.length === 1) {
        return wordWithTwoDefinitionFind.defaultValue;
      } else {
        const strfind = valSplit[i + 1]
          .toLowerCase()
          .normalize("NFD")
          .replace(/[\u0300-\u036f]/g, "");
        for (let option of PaymentOptions) {
          if (option.value === "other") continue;
          if (option.keywords.includes(strfind)) return option.value as string;
        }
      }
    }
    const strfind = val
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "");
    for (let option of PaymentOptions) {
      if (option.value === "other") continue;
      if (option.keywords.includes(strfind)) return option.value as string;
    }
  }
  return "other";
};

const wordWithTwoDefinition: { key: string; defaultValue: string }[] = [
  {
    key: "e leclerc",
    defaultValue: "foodrace",
  },
  {
    key: "e.leclerc",
    defaultValue: "foodrace",
  },
  {
    key: "leclerc",
    defaultValue: "foodrace",
  },
  {
    key: "carrefour",
    defaultValue: "foodrace",
  },
  {
    key: "auchan",
    defaultValue: "foodrace",
  },
  {
    key: "orange",
    defaultValue: "internet",
  },
  {
    key: "sfr",
    defaultValue: "internet",
  },
  {
    key: "bouygues",
    defaultValue: "internet",
  },
  {
    key: "amazon",
    defaultValue: "onlineshopping",
  },
  {
    key: "cdiscount",
    defaultValue: "onlineshopping",
  },
  {
    key: "ebay",
    defaultValue: "onlineshopping",
  },
  {
    key: "veepee",
    defaultValue: "onlineshopping",
  },
  {
    key: "vente privee",
    defaultValue: "onlineshopping",
  },
  {
    key: "showroom",
    defaultValue: "onlineshopping",
  },
  {
    key: "google",
    defaultValue: "onlineshopping",
  },
  {
    key: "uber",
    defaultValue: "car",
  },
];

type PaymentOptionsProps = {
  keywords: string[];
} & DropdownItemProps;

export const PaymentOptions: PaymentOptionsProps[] = [
  {
    key: "salary",
    icon: "file alternate",
    text: "Salaire",
    value: "salary",
    keywords: ["salaire", "pay", "fiche de pay", "bulletin"],
  },
  {
    key: "home",
    icon: "home",
    text: "Maison",
    value: "home",
    keywords: [
      "loyer",
      "echeance",
      "appartement",
      "maison",
      "domicile",
      "ikea",
      "alinea",
      "darty",
      "made",
      "but",
    ],
  },
  {
    key: "gaselectricity",
    icon: "bolt",
    text: "Electricite / Gaz",
    value: "gaselectricity",
    keywords: [
      "electricite",
      "gaz",
      "energie",
      "chauffage",
      "edf",
      "engie",
      "eni",
      "total energie",
      "mega energie",
      "vattenfall",
      "planete oui",
      "ilek",
      "mint energie",
      "butagaz",
      "greenyellow",
      "antargaz",
      "cdiscount energie",
      "happ-e",
      "ohm energie",
      "iberdrola",
      "energies e.leclerc",
      "enercoop",
      "wekiwi",
      "ekwateur",
      "sowee",
      "plum energie",
      "ovo energy",
      "electrcite de provence",
      "alterna",
      "bulb",
      "elecocite",
      "energem",
      "energie d'ici",
      "gaz de bordeaux",
      "geg",
      "proxelia",
      "selia",
      "urban solar energy",
      "dyneff gaz",
      "energies du santerre",
      "lucia energie",
    ],
  },

  {
    key: "foodrace",
    icon: "cart",
    text: "Course alimentaire",
    value: "foodrace",
    keywords: [
      "course",
      "courses",
      "alimentaire",
      "nourriture",
      "picard",
      "grand frais",
      "thiriet",
      "auchan",
      "lidl",
      "systeme u",
      "intermarche",
      "geant",
      "market",
      "franprix",
      "cora",
      "leader price",
      "simply",
      "magasin u",
      "monoprix",
      "vival",
      "spar",
      "casino",
      "aldi",
      "sherpa",
    ],
  },
  {
    key: "mobile",
    icon: "mobile alternate",
    text: "Téléphone",
    value: "mobile",
    keywords: ["mobile", "portable", "telephone"],
  },
  {
    key: "internet",
    icon: "at",
    text: "Internet",
    value: "internet",
    keywords: ["internet", "web", "box"],
  },
  {
    key: "movie",
    icon: "film",
    text: "Vidéo à la demande",
    value: "movie",
    keywords: [
      "vod",
      "video a la demande",
      "netflix",
      "prime",
      "video",
      "disney+",
      "disney plus",
      "hulu",
      "apple tv+",
      "hbo max",
      "ocs",
      "orange cinema series",
      "canal plus",
      "canal +",
      "canal+ series",
      "youtube",
      "dailymotion",
      "facebook watch",
      "vimeo",
    ],
  },
  {
    key: "music",
    icon: "music",
    text: "Musique à la demande",
    value: "music",
    keywords: [
      "musique",
      "spotify",
      "apple music",
      "youtube",
      "deezer",
      "itunes",
    ],
  },

  {
    key: "car",
    icon: "car",
    text: "Véhicule",
    value: "car",
    keywords: ["assurance voiture", "essence", "reparation"],
  },
  {
    key: "bar",
    icon: "bar",
    text: "Activitée exterieur",
    value: "bar",
    keywords: [
      "sortie",
      "activite",
      "activitee",
      "sorties",
      "bar",
      "cinema",
      "parc",
      "boite",
      "club",
      "disneyland",
      "asterix",
      "spectacle",
      "concert",
      "festival",
    ],
  },

  {
    key: "medkit",
    icon: "medkit",
    text: "Frais medicaux",
    value: "medkit",
    keywords: ["medecin", "hopital", "medical"],
  },
  {
    key: "pet",
    icon: "paw",
    text: "Animaux de compagnie",
    value: "pet",
    keywords: [
      "veterinaire",
      "chien",
      "chat",
      "furet",
      "rat",
      "cochon",
      "hamster",
      "chinchilla",
      "degue du chili",
      "gerbille",
      "souris",
      "lapin",
      "alpaga",
      "cheval",
      "ane",
      "chevre",
      "oiseau",
      "poissons",
      "lezard",
      "serpent",
      "tortue",
      "axoloti",
      "grenouille",
      "triton",
    ],
  },
  {
    key: "restaurant",
    icon: "food",
    text: "Restaurant",
    value: "restaurant",
    keywords: [
      "restaurant",
      "eat",
      "justeat",
      "deliveroo",
      "brasserie",
      "pizza",
      "japonais",
      "burger",
      "indien",
      "pakistanais",
      "chinois",
    ],
  },
  {
    key: "viedogame",
    icon: "gamepad",
    text: "Divertissement",
    value: "viedogame",
    keywords: ["ps4", "playstation", "xbox", "jeux", "jeu", "console", "livre"],
  },
  {
    key: "donation",
    icon: "heart",
    text: "Donation",
    value: "donation",
    keywords: [
      "don",
      "dons",
      "donation",
      "association",
      "associations",
      "croix rouge",
      "sos",
      "secours",
      "amnesty",
      "uniceff",
      "handicap",
      "armee",
      "action",
      "peta",
      "bardot",
      "30 millions",
      "greenpeace",
      "spa",
      "wwf",
    ],
  },
  {
    key: "university",
    icon: "university",
    text: "Etude",
    value: "university",
    keywords: [
      "primaire",
      "college",
      "fac",
      "ecole",
      "universite",
      "scolarite",
    ],
  },
  {
    key: "transport",
    icon: "subway",
    text: "Transport en commun",
    value: "transport",
    keywords: ["metro", "bus", "transport", "rer", "navigo"],
  },

  {
    key: "travel",
    icon: "plane",
    text: "Voyage",
    value: "travel",
    keywords: [
      "voyage",
      "train",
      "avion",
      "afghanistan",
      "afrique du sud",
      "albanie",
      "algerie",
      "allemagne",
      "andorre",
      "angola",
      "anguilla",
      "antarctique",
      "antigua-et-barbuda",
      "antilles neerlandaises",
      "arabie saoudite",
      "argentine",
      "armenie",
      "aruba",
      "australie",
      "autriche",
      "azerbaidjan",
      "bahamas",
      "bahrein",
      "bangladesh",
      "barbade",
      "belarus",
      "belgique",
      "belize",
      "benin",
      "bermudes",
      "bhoutan",
      "bolivie",
      "bosnie-herzegovine",
      "botswana",
      "bresil",
      "brunei darussalam",
      "bulgarie",
      "burkina faso",
      "burundi",
      "cambodge",
      "cameroun",
      "canada",
      "cap-vert",
      "ceuta et melilla",
      "chili",
      "chine",
      "chypre",
      "colombie",
      "comores",
      "congo-brazzaville",
      "coree du nord",
      "coree du sud",
      "costa rica",
      "côte d’ivoire",
      "croatie",
      "cuba",
      "danemark",
      "diego garcia",
      "djibouti",
      "dominique",
      "egypte",
      "el salvador",
      "emirats arabes unis",
      "equateur",
      "erythree",
      "espagne",
      "estonie",
      "etat de la cite du vatican",
      "etats federes de micronesie",
      "etats-unis",
      "ethiopie",
      "fidji",
      "finlande",
      "france",
      "gabon",
      "gambie",
      "georgie",
      "georgie du sud et les îles sandwich du sud",
      "ghana",
      "gibraltar",
      "grece",
      "grenade",
      "groenland",
      "guadeloupe",
      "guam",
      "guatemala",
      "guernesey",
      "guinee",
      "guinee equatoriale",
      "guinee-bissau",
      "guyana",
      "guyane francaise",
      "haiti",
      "honduras",
      "hongrie",
      "ile",
      "ile bouvet",
      "ile christmas",
      "ile clipperton",
      "ile de l'ascension",
      "ile de man",
      "ile norfolk",
      "iles Åland",
      "iles caimans",
      "iles canaries",
      "iles cocos - keeling",
      "iles cook",
      "iles feroe",
      "iles heard et macdonald",
      "iles malouines",
      "iles mariannes du nord",
      "iles marshall",
      "iles mineures eloignees des etats-unis",
      "iles salomon",
      "iles turks et caiques",
      "iles vierges britanniques",
      "iles vierges des etats-unis",
      "inde",
      "indonesie",
      "irak",
      "iran",
      "irlande",
      "islande",
      "israel",
      "italie",
      "jamaique",
      "japon",
      "jersey",
      "jordanie",
      "kazakhstan",
      "kenya",
      "kirghizistan",
      "kiribati",
      "koweit",
      "laos",
      "lesotho",
      "lettonie",
      "liban",
      "liberia",
      "libye",
      "liechtenstein",
      "lituanie",
      "luxembourg",
      "macedoine",
      "madagascar",
      "malaisie",
      "malawi",
      "maldives",
      "mali",
      "malte",
      "maroc",
      "martinique",
      "maurice",
      "mauritanie",
      "mayotte",
      "mexique",
      "moldavie",
      "monaco",
      "mongolie",
      "montenegro",
      "montserrat",
      "mozambique",
      "myanmar",
      "namibie",
      "nauru",
      "nepal",
      "nicaragua",
      "niger",
      "nigeria",
      "niue",
      "norvege",
      "nouvelle-caledonie",
      "nouvelle-zelande",
      "oman",
      "ouganda",
      "ouzbekistan",
      "pakistan",
      "palaos",
      "panama",
      "papouasie-nouvelle-guinee",
      "paraguay",
      "pays-bas",
      "perou",
      "philippines",
      "pitcairn",
      "pologne",
      "polynesie",
      "polynesie francaise",
      "porto rico",
      "portugal",
      "qatar",
      "r.a.s. chinoise de hong kong",
      "r.a.s. chinoise de macao",
      "regions eloignees de l’oceanie",
      "republique centrafricaine",
      "republique democratique du congo",
      "republique dominicaine",
      "republique tcheque",
      "reunion",
      "roumanie",
      "royaume-uni",
      "russie",
      "rwanda",
      "sahara occidental",
      "saint-barthelemy",
      "saint-kitts-et-nevis",
      "saint-marin",
      "saint-martin",
      "saint-pierre-et-miquelon",
      "saint-vincent-et-les grenadines",
      "sainte-helene",
      "sainte-lucie",
      "samoa",
      "samoa americaines",
      "sao tome-et-principe",
      "senegal",
      "serbie",
      "serbie-et-montenegro",
      "seychelles",
      "sierra leone",
      "singapour",
      "slovaquie",
      "slovenie",
      "somalie",
      "soudan",
      "sri lanka",
      "suede",
      "suisse",
      "suriname",
      "svalbard et ile jan mayen",
      "swaziland",
      "syrie",
      "tadjikistan",
      "taiwan",
      "tanzanie",
      "tchad",
      "terres australes francaises",
      "territoire britannique de l'ocean indien",
      "territoire palestinien",
      "thailande",
      "timor oriental",
      "togo",
      "tokelau",
      "tonga",
      "trinite-et-tobago",
      "tristan da cunha",
      "tunisie",
      "turkmenistan",
      "turquie",
      "tuvalu",
      "ukraine",
      "union europeenne",
      "uruguay",
      "vanuatu",
      "venezuela",
      "viêt nam",
      "wallis-et-futuna",
      "yemen",
      "zambie",
      "zimbabwe",
    ],
  },
  {
    key: "onlineshopping",
    icon: "amazon",
    text: "Achat sur internet",
    value: "onlineshopping",
    keywords: ["Achat sur internet", "delabs"],
  },
  {
    key: "shopping",
    icon: "shopping basket",
    text: "Vétement",
    value: "shopping",
    keywords: [
      "shopping",
      "vetement",
      "vetements",
      "bascket",
      "chaussure",
      "chaussures",
      "robe",
      "tee-shirt",
      "t-shirts",
      "t-shirt",
      "polos",
      "chemises",
      "pulls",
      "vestes",
      "menteaux",
      "jeans",
      "manteaux",
      "costumes",
      "pantalons",
      "shorts",
      "costumes",
      "survetements",
      "sous-vetements",
      "maillots",
      "pyjamas",
      "zalando",
      "kiabi",
      "jennyfer",
      "pimkie",
      "promod",
      "graindmalice",
      "camaieu",
      "gemo",
      "cache-cache",
      "bonoboplanet",
      "boohoo",
      "asos",
      "la halle",
      "princesse boutique",
      "caroll",
      "uniqlo",
      "jules",
      "linguee",
      "tati",
      "petit bateau",
      "brice",
      "etam",
      "reebok",
      "decathlon",
      "besson",
      "andre",
      "sarenza",
      "eram",
      "mineli",
      "courir",
      "locker",
    ],
  },
  {
    key: "sport",
    icon: "futbol",
    text: "Sport",
    value: "sport",
    keywords: [
      "sport",
      "football",
      "basketball",
      "tennis",
      "badminton",
      "baseball",
      "danse",
      "echecs",
      "equitation",
      "gymnastique",
      "handball",
      "hockey",
      "judo",
      "karate",
      "combat",
      "contact",
      "boxe",
      "club",
      "salle",
      "muscu",
      "musculation",
      "kenjutsu",
      "boxing",
      "krav maga",
      "natation",
    ],
  },
  {
    key: "credit",
    icon: "money bill alternate outline",
    text: "Crédit",
    value: "credit",
    keywords: [
      "credit",
      "cetelem",
      "banque",
      "younited",
      "sofinco",
      "bank",
      "n26",
      "revolute",
      "boursorama",
      "boursorama-banque",
      "monabanq",
    ],
  },
  {
    key: "insurance",
    icon: "building",
    text: "Assurance",
    value: "insurance",
    keywords: [
      "assurance",
      "macif",
      "nexx",
      "gan",
      "groupama",
      "maaf",
      "agf",
      "axa",
      "eurofil",
      "direct assurance",
      "azur",
      "aviva",
      "mma",
      "assuroline",
      "generali assurance",
      "allianz",
      "netassurance",
      "gmf",
      "malakoff",
      "cic",
      "olivier assurance",
      "swiss",
      "cetelem",
    ],
  },
  {
    key: "gavel",
    icon: "gavel",
    text: "Frais juridique",
    value: "gavel",
    keywords: ["frais juridique", "avocat", "amende", "amendes", "notaire"],
  },
  {
    key: "cut",
    icon: "cut",
    text: "Coiffeur / Esthéticienne",
    value: "cut",
    keywords: [
      "coiffeur",
      "estheticienne",
      "cheveux",
      "ongle",
      "ongles",
      "brushing",
      "couleur",
      "epilation",
      "manucure",
      "coupe",
      "massage",
      "soins",
      "franck provost",
      "dessange",
      "bio coiff",
      "fabio salsa",
      "camille",
      "jean louis david",
      "saint algue",
    ],
  },
  {
    key: "newspaper",
    icon: "newspaper",
    text: "Actualitées (site d'information, journaux, ...)",
    value: "newspaper",
    keywords: [
      "actualitee",
      "actualite",
      "actu",
      "info",
      "infos",
      "information",
      "informations",
      "figaro",
      "express",
      "mediapart",
      "tvl",
      "parisien",
      "le monde",
      "linternaute",
      "hitek",
      "journal du geek",
      "france24",
      "francetvinfo",
      "france télévision",
      "tv5",
      "01net",
      "20 minutes",
      "chanllenges",
      "dna",
      "europe1",
      "france 2",
      "france 3",
      "france 5",
      "le point",
      "l'equipe",
      "les echos",
      "liberation",
      "nouvelobs",
      "paris match",
      "radio france",
      "rtl",
      "tf1",
      "capital",
      "le jdd",
      "ouest-france",
      "rmc",
      "closer",
      "telerama",
      "la depeche",
    ],
  },
  {
    key: "withdrawal",
    icon: "id card",
    value: "withdrawal",
    text: "Retrait d'argent",
    keywords: ["liquide", "monnaie", "retrait", "argent", "euros"],
  },
  {
    key: "other",
    icon: "file",
    text: "Autre",
    value: "other",
    keywords: [],
  },
];
